#!/bin/bash


function flatpakinstall() {

    LOGFILE="$1"
    DIRBIN="$2"
    APPNAME="$3"
    GETREMOTES="$4"
    GETAPPID="$5"
    GETDISPLAY="$6"

    (
    zenity --info --title="処理中" --display=$GETDISPLAY --text="このウィンドウが自動で閉じるまで待って下さい" &
    GETPID=`echo $!`
    echo "ソフト名:" 
    echo $APPNAME 
    echo "" 
    echo "remotes,Application ID:" 
    echo $GETREMOTES","$GETAPPID 
    echo "" 
    echo "処理結果:" 

    flatpak install -y $GETREMOTES $GETAPPID 
    if [ $? == 0 ]
    then
        echo "" 
        echo "############################################################################"
        echo "flatpak run --command=fc-cache "$GETAPPID" -f -v"

        flatpak run --command=fc-cache $GETAPPID -f -v 

        if [ `echo "$GETAPPID" | grep "Plugin" | wc -l` = 0  ]
        then
            TMPNAME=`echo "$GETAPPID" | cut -f 3 -d "." | tr '[:upper:]' '[:lower:]'`
            RAPNAME=$DIRBIN"/"$TMPNAME
            echo "#!/bin/bash" > $RAPNAME
            echo "flatpak run "$GETAPPID >> $RAPNAME
            chown $GETUSER:$GETUSER $RAPNAME
            chmod +x $RAPNAME
            zenity --info --title="実行方法" --display=$GETDISPLAY --text=`echo $RAPNAME`"で実行できます" &
        else
            zenity --info --title="確認" --display=$GETDISPLAY --text="プラグインをインストールしました" &
        fi
    else
        zenity --error --display=$GETDISPLAY --text="インストールに失敗しました" &
    fi
    kill $GETPID
    ) 2>&1 | tee -a $LOGFILE | \
        zenity --text-info --title="「flatpakでインストール」の処理結果" \
        --width=600  --height=400 --display=$GETDISPLAY  \
        --auto-scroll --checkbox="処理終了を確認"

 }
