#!/bin/bash

cd `dirname $0`
DIRBIN=$HOME/.local/myflatpak
xhost +local:
GETSEL=`zenity --list --title="処理選択" \
        --print-column=1 --column="ID" --column="処理内容" \
        --width=600  --height=400 \
        "01" "aptでインストール" \
        "02" "flatpakでインストール" \
        "08" "flatpakで探してインストール" \
        "03" "flatpakの文字化け改善" \
        "04" "flatpakのソフト起動" \
        "05" "flatpakのソフト更新" \
        "06" "flatpakの全てのソフト更新" \
        "07" "flatpakのソフト削除" `
echo $GETSEL
if [ "$GETSEL" = "01" ]
then
    pkexec bash  `pwd`/apt_install.sh `pwd` $DISPLAY

elif [ "$GETSEL" = "02" ]
then
    pkexec bash  `pwd`/flatpak_install.sh `pwd` $DISPLAY $DIRBIN $USER

elif [ "$GETSEL" = "03" ]
then
    bash  `pwd`/flatpak_fc-cache.sh $DISPLAY $DIRBIN

elif [ "$GETSEL" = "04" ]
then
    bash  `pwd`/run_flatpak.sh $DISPLAY $DIRBIN

elif [ "$GETSEL" = "05" ]
then
    bash  `pwd`/flatpak_update.sh $DISPLAY $DIRBIN

elif [ "$GETSEL" = "06" ]
then
    bash  `pwd`/flatpak_allupdate.sh $DISPLAY

elif [ "$GETSEL" = "07" ]
then
    bash  `pwd`/flatpak_uninstall.sh $DISPLAY $DIRBIN

elif [ "$GETSEL" = "08" ]
then
    pkexec bash  `pwd`/flatpak_search-install.sh `pwd` $DISPLAY $DIRBIN $USER

else
    zenity --error --text="処理が選択されていません"
fi
xhost -
